# 雷达标记进度数据 (命令码: 0x020C)
# 以1Hz频率发送给雷达机器人

# 对方机器人易伤情况
bool enemy_hero_marked           # 对方1号英雄机器人
bool enemy_engineer_marked       # 对方2号工程机器人
bool enemy_infantry_3_marked     # 对方3号步兵机器人
bool enemy_infantry_4_marked     # 对方4号步兵机器人
bool enemy_aerial_marked         # 对方空中机器人
bool enemy_sentry_marked         # 对方哨兵机器人

# 己方机器人特殊标识情况
bool ally_hero_marked            # 己方1号英雄机器人
bool ally_engineer_marked        # 己方2号工程机器人
bool ally_infantry_3_marked      # 己方3号步兵机器人
bool ally_infantry_4_marked      # 己方4号步兵机器人
bool ally_aerial_marked          # 己方空中机器人
bool ally_sentry_marked          # 己方哨兵机器人
