# 机器人血量数据 (命令码: 0x0003)
# 以3Hz频率发送

# 红方机器人血量
uint16 red_1_robot_hp      # 己方1号英雄机器人血量
uint16 red_2_robot_hp      # 己方2号工程机器人血量
uint16 red_3_robot_hp      # 己方3号步兵机器人血量
uint16 red_4_robot_hp      # 己方4号步兵机器人血量
uint16 red_7_robot_hp      # 己方7号哨兵机器人血量
uint16 red_outpost_hp      # 己方前哨站血量
uint16 red_base_hp         # 己方基地血量

# 蓝方机器人血量
uint16 blue_1_robot_hp     # 对方1号英雄机器人血量
uint16 blue_2_robot_hp     # 对方2号工程机器人血量
uint16 blue_3_robot_hp     # 对方3号步兵机器人血量
uint16 blue_4_robot_hp     # 对方4号步兵机器人血量
uint16 blue_7_robot_hp     # 对方7号哨兵机器人血量
uint16 blue_outpost_hp     # 对方前哨站血量
uint16 blue_base_hp        # 对方基地血量
